### ISSUE TITLE
cannot launch node of type [ctlo/ctlo]

### ISSUE THREAD

**Issue by tops666** [chengwei0427/CTLO#2]
thank you for your project . when I test it ,there was an error.

ERROR: cannot launch node of type [ctlo/ctlo]: Cannot locate node of type [ctlo] in package [ctlo]. Make sure file exists in package path and permission is set to executable (chmod +x)

**Comment by chengwei0427** [comment]
`source  ./devel/setup.bash`   before run the launch

**Comment by tops666** [comment]
程序运行前，source 工作空间，还是报 ERROR: cannot launch node of type [ctlo/ctlo]: Cannot locate node of type [ctlo] in package [ctlo]. Make sure file exists in package path and permission is set to executable (chmod +x)

**Comment by chengwei0427** [comment]
It is recommended that you verify the location and name of the executable file you generated before running it. It's a simple question, and I'm sure you can solve it;
