### ISSUE TITLE
很棒的工作，mid360要怎么运行呢？

### ISSUE THREAD

**Issue by itototototo** [chengwei0427/CTLO#3]
我修改了mapping.yaml文件，但即使改成6 livox，但启动不成功

**Comment by chengwei0427** [comment]
你好，感谢关注！
可以在[这里](https://github.com/chengwei0427/CTLO/blob/ee05ade3e261ed04c3a7334c3b730c350d1a221e/config/mapping.yaml#L5C11-L5C11)修改为AVIA就可以了。
