### ISSUE TITLE
关于残差方程的问题

### ISSUE THREAD

**Issue by codehory** [chengwei0427/CTLO#4]
作者你好，
有个问题想请教下:
关于点到面的平面的距离公式：point_to_plane_dist = std::abs((keypoint.point - vector_neighbors[i]).transpose() * neighborhood.normal); 我理解是当前点与近邻点组成的向量在平面法向量上的投影，这个值近似为点到平面的距离。
对于这个offset值的计算，double norm_offset = -norm_vector.dot(vector_neighbors[i]); 我不是很理解他的含义，残差方程double distance = norm_vector.dot(point_world) + norm_offset 中用到了这个值，麻烦作者解惑！

十分感谢你的分享！

**Comment by chengwei0427** [comment]
Hi, @codehory 
Thanks for your interesting in our project.
'double norm_offset = -norm_vector.dot(vector_neighbors[i])' is a line-function formula use a normal vector and a point on the line.

**Comment by codehory** [comment]
感谢你的回复，
我明白了，其实point_to_plane_dist = std::abs((keypoint.point - vector_neighbors[i]).transpose() * neighborhood.normal)和distance = norm_vector.dot(point_world) + norm_offset 这两个公式描述的是一个距离，只不过后一个把公式拆开写了。我理解的没错吧。
