### ISSUE TITLE
Dataset Download

### ISSUE THREAD

**Issue by satyajitghana** [chengwei0427/CTLO#5]
Hi @chengwei0427 

I cannot download the dataset from baidu: https://pan.baidu.com/s/1Jg0lOT_FQt-jE0o4d0pOlg

can you please share this over google drive.

We're trying to test our SLAM algorithm and compare it with CTLO. And want to test out your dataset

**Comment by satyajitghana** [comment]
specifically https://github.com/chengwei0427/CTLO#mid-360 and https://github.com/chengwei0427/CTLO#mid-360-multi-layer

**Comment by satyajitghana** [comment]
also do you have any dataset with rotating MID360?

**Comment by chengwei0427** [comment]
Hi, @satyajitghana 
You can download the dataset here:
1.  https://www.youtube.com/watch?v=adALW9jCwtc&t=71s
2. https://www.youtube.com/watch?v=u8siB0KLFLc&t=346s

**Comment by satyajitghana** [comment]
thanks @chengwei0427 :)
